// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "wishlist-go/model"

	mock "github.com/stretchr/testify/mock"
)

// Repositorier is an autogenerated mock type for the Repositorier type
type Repositorier struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *Repositorier) Create(req []model.WishlistRequest) ([]model.Wishlist, error) {
	ret := _m.Called(req)

	var r0 []model.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func([]model.WishlistRequest) ([]model.Wishlist, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func([]model.WishlistRequest) []model.Wishlist); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func([]model.WishlistRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: userID, wishlistID
func (_m *Repositorier) Delete(userID int, wishlistID int) error {
	ret := _m.Called(userID, wishlistID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(userID, wishlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: userID
func (_m *Repositorier) Get(userID int) ([]model.Wishlist, error) {
	ret := _m.Called(userID)

	var r0 []model.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]model.Wishlist, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []model.Wishlist); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Wishlist)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetail provides a mock function with given fields: userID, wishlistID
func (_m *Repositorier) GetDetail(userID int, wishlistID int) (model.Wishlist, error) {
	ret := _m.Called(userID, wishlistID)

	var r0 model.Wishlist
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (model.Wishlist, error)); ok {
		return rf(userID, wishlistID)
	}
	if rf, ok := ret.Get(0).(func(int, int) model.Wishlist); ok {
		r0 = rf(userID, wishlistID)
	} else {
		r0 = ret.Get(0).(model.Wishlist)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(userID, wishlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepositorier interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositorier creates a new instance of Repositorier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositorier(t mockConstructorTestingTNewRepositorier) *Repositorier {
	mock := &Repositorier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
