INSERT INTO countries (name, calling_code) VALUES
('United States', '+1'),
('Canada', '+1'),
('China', '+86'),
('India', '+91'),
('United Kingdom', '+44'),
('Germany', '+49'),
('France', '+33'),
('Australia', '+61'),
('Russia', '+7'),
('Japan', '+81'),
('South Korea', '+82'),
('Indonesia', '+62'),
('Brazil', '+55'),
('Mexico', '+52'),
('South Africa', '+27'),
('Nigeria', '+234'),
('Egypt', '+20'),
('Turkey', '+90'),
('Saudi Arabia', '+966'),
('United Arab Emirates', '+971');
