INSERT INTO languages (name) VALUES
('English'),
('Bahasa Indonesia'),
('Mandarin Chinese'),
('Spanish'),
('Hindi'),
('Bengali'),
('Portuguese'),
('Russian'),
('Japanese'),
('Western Punjabi'),
('Marathi'),
('Telugu'),
('Wu Chinese'),
('Turkish'),
('Korean'),
('French'),
('German'),
('Vietnamese'),
('Tamil'),
('Yue Chinese'),
('Urdu');